FROM node:18.18.0
# 작업 디렉터리 설정
WORKDIR /frontend

# 현재 디렉터리의 모든 파일과 디렉터리를 컨테이너의 /frontend 디렉터리로 복사
COPY . .

# npm을 사용하여 종속성 설치
RUN npm install

# Vite를 전역적으로 설치
RUN npm install vite

#RUN mkdir -p /frontend/node_modules/.vite && chown -R 1000:1000 /frontend/node_modules

RUN npm run build

# 컨테이너 시작 시 실행될 명령 설정
CMD ["npm", "run", "dev"]