version: 0.0
os: linux

files:
  - source: /
    destination: /opt/achieve/project
file_exists_behavior: OVERWRITE
permissions:
  - object: /opt/achieve/project
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh

  AfterInstall:
    - location: scripts/deploy.sh
#      timeout: 60
      runas: root
