version: 0.0
os: linux

files:
  - source: /
    destination: /opt/achieve/project
file_exists_behavior: OVERWRITE
permissions:
  - object: /opt/achieve/project
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 3000
      runas: root