services:
  grafana: # 그라파나 서비스 추가
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./devops/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./devops/monitoring/grafana/grafana-data:/var/lib/grafana
    user: root
    depends_on:
      - prometheus

  prometheus: # 프로메테우스 서비스 추가
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./devops/monitoring/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:v0.47.0
#    container_name: cadvisor
#    privileged: true
#    ports:
#      - "9000:8082"
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /proc/cpuinfo:/host/proc/cpuinfo:ro
#      - /dev/disk:/dev/disk/:ro
#    devices:
#      - /dev/kmsg:/dev/kmsg

#  influxdb:
#    image: influxdb:1.8
#    ports:
#      - "8086:8086"
#    environment:
#      - INFLUXDB_DB=k6
#
#  k6:
#    image: grafana/k6:latest
#    platform: linux/amd64
#    ports:
#      - "6565:6565"
#    environment:
#      - K6_OUT=influxdb=http://influxdb:8086/k6
#    volumes:
#      - ./backend/monitoring/k6:/scripts
#    command: run /scripts/load.js

#  node-exporter:
#    image: prom/node-exporter:latest
#    ports:
#      - "9100:9100"