version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: achieve
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - "3307:3306"


  backend:
    container_name: backend
    build:
      context: backend # dockerfile의 위치
      dockerfile: dockerfile
    environment:
      WAIT_HOSTS: mysql:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achieve?createDatabaseIfNotExist=true&characterEncoding=UTF-8&profileSql=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis

    command: ["java", "-jar", "/app.jar"]
    volumes:
      - ./backend:/app
      - ./backend/target/classes:/app/classes

  redis:
    hostname: redis
    container_name: redis
    image: redis:latest
    ports:
      - 6380:6379
    restart: always
volumes:
  db_data:
