version: "3.8"

services:
  k6:
    container_name: k6
    image: grafana/k6:latest
    platform: linux/amd64
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./devops/monitoring/k6:/scripts
    command: run /scripts/load.js
