version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: achieve
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - "3307:3306"


  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: dockerfile-dev
    environment:
      WAIT_HOSTS: mysql:3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/achieve?createDatabaseIfNotExist=true&characterEncoding=UTF-8&profileSql=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    command: ["java", "-jar", "/app.jar"]
    volumes:
      - ./backend:/app
      - ./backend/target/classes:/app/classes

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: dockerfile
    command: [ "npm", "run", "dev" ]
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - ./frontend/.npm/_cacache:/frontend/.npm/_cacache
      - build_folder:/frontend/dist
    ports:
      - "5173:5173"
    tty: true
    environment:
      - npm_config_cache=/frontend/.npm/_cacache
    depends_on:
      - backend

  redis:
    hostname: redis
    container_name: redis
    image: redis:latest
    ports:
      - 6380:6379
    restart: always

  nginx:
    container_name: nginx
    build:
      context: devops/nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./devops/nginx/nginx_develop.conf:/etc/nginx/nginx.conf
      - build_folder:/var/www/frontend
    depends_on:
      - backend
    expose:
      - '80'
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''


volumes:
  mysql_data:
  build_folder: