version: "3.8"

services:
  backend:
    container_name: backend-green
    build:
      context: backend
      dockerfile: dockerfile-prod
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8080"
    depends_on:
      - redis
    command: ["java", "-jar", "/app.jar"]
    volumes:
      - ./backend:/app
      - ./backend/target/classes:/app/classes

  frontend:
    container_name: frontend-green
    build:
      context: frontend
      dockerfile: dockerfile
    command: [ "npm", "run", "dev" ]
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - ./frontend/.npm/_cacache:/frontend/.npm/_cacache
      - build_folder:/frontend/dist
    ports:
      - "5173:5173"
    tty: true
    environment:
      - npm_config_cache=/frontend/.npm/_cacache
    depends_on:
      - backend-green

  redis:
    hostname: redis
    container_name: redis
    image: redis:latest
    ports:
      - 6380:6379
    restart: always

volumes:
  mysql_data:
  build_folder:
