FROM openjdk:11-jdk-slim as Build
ENV SPRING_PROFILES_ACTIVE=docker

COPY . /app

# 작업 디렉터리 설정
WORKDIR /app

# gradlew에 실행 권한 부여
RUN chmod +x gradlew

RUN ./gradlew build -x test

FROM openjdk:11-jdk-slim
ENV SPRING_PROFILES_ACTIVE=docker

ARG JAR_FILE=build/libs/backend-0.0.1-SNAPSHOT.jar
COPY --from=Build /app/${JAR_FILE} app.jar

EXPOSE 8080

COPY wait-for-it.sh wait-for-it.sh
RUN chmod +x wait-for-it.sh
ENTRYPOINT ["./wait-for-it.sh", "mysql:3306", "-s", "-t", "100", "--"]