global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
    #metrics_path: '/custom-metrics'
    params:
      status: ['200', '201','204', '401', '403', '404', '500']
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8082']

  - job_name: 'backend'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: [ 'backend:8080', 'backend:8081']

#rule_files:
#  - ./alert.rules.yml

#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
#            - alertmanager:9093
