Spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/achieve?serverTimezone=Asia/Seoul&autoReconnect=true&createDatabaseIfNotExist=true
    username: root
    password: dina4998
  redis:
    host: localhost
    port: 6379

  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    open-in-view: false


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

