---
spring:
  profiles:
    active: local
    include: oauth
---
spring:
  profiles:
    active: dev
    include: oauth
---
spring:
  profiles:
    active: prod
    include: oauth
---
spring:
  profiles:
    active: test
    include: oauth